name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'pages/**'
      - 'public/**'
      - '.vitepress/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_URL: "CASANOVA97/CASANOVA97.github.io"
      BUILD_PATH: "dist"                 # ✅ 修改：Astro 默认输出目录
      CUSTOM_DOMAIN: "casanova.asia"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'                  # ✅ 启用 pnpm 缓存

      - name: Setup pnpm                 # ✅ 必须在 Node 之后、install 之前
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Ensure sharp present       # ✅ 临时安装 sharp 避免 MissingSharp
        run: pnpm add sharp

      - name: Approve native builds      # ✅ 允许执行原生构建脚本（pnpm v10 需要）
        run: pnpm approve-builds sharp esbuild @parcel/watcher

      - name: Build project
        run: pnpm run build

      - name: Deploy to GitHub Pages
        run: |
          cd "$BUILD_PATH"
          echo "$CUSTOM_DOMAIN" > CNAME
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git checkout -B pages
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.REPO_URL }}.git
          git push --force origin pages
        env:
          CI: true
